# Generated by Django 3.0 on 2022-04-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsig_blog', '0002_auto_20220401_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
